### ISSUE TITLE
Barometer Medium Level Issue

### ISSUE THREAD

**Issue by csomph00** [UARK-Quadcopter-Flight-Controller/STM32F4_PeripheralTest#5]
Research SDI and SDO connection issue from Barometer to MCU

Apparently the SDI and SDO lines are reversed.

Our connection Currently:
SDI connected to SDI
SDO connected to SDO

Needs to:
SDI connected to SDO
SDO connects to SDI 

Link:
https://electronics.stackexchange.com/questions/345393/spi-naming-sdi-mosi-confusion

**Comment by Dishoungh** [comment]
I am getting values in the revised board Zach gave me, but the problem still remains that the calibration data is coming out wrong. I don't know what's going on with it and I'll investigate it further.

**Comment by Dishoungh** [comment]
@csomph00  Since the issue seems to be resolved (it's under completed in the Projects list), should this issue be closed?

**Comment by csomph00** [comment]
@Dishoungh Thanks.Yes it should be closed since the hardware seems to been fixed
